# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVMPlayground' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVMPlayground
  pod 'SDWebImage', '~> 4.0'
  target 'MVVMPlaygroundTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
